# Generated by Django 5.0.4 on 2024-04-12 17:26

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
