# Generated by Django 5.0.4 on 2024-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_like_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
