# Generated by Django 5.0.4 on 2024-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
