# Generated by Django 5.0.4 on 2024-04-18 16:17

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_like_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
