# Generated by Django 5.0.4 on 2024-04-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='recipes.recipe'),
        ),
    ]
