# Generated by Django 5.0.4 on 2024-04-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, default='Users/Profile_images/default.jpg', null=True, upload_to='Users/Profile_images'),
        ),
    ]
