# Generated by Django 5.0.4 on 2024-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, default='Users/Profile_images/default.jpg', null=True, upload_to='Users/Profile_images'),
        ),
    ]
