# Generated by Django 5.0.4 on 2024-04-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='Users/Profile_images'),
        ),
    ]
